name = "docs"
account_id = "fadc7c4786d4e9b9ef650985a9282c82"
type = "webpack"
# workers_dev = true
route = "docs.htmlcsstoimage.com/*"
zone_id = "afe7c7febba92b591f139226a076a193"
compatibility_date = "2024-12-18"

[site]
bucket = "./_site"
