// Explicit navigation preserves the established sections and URLs.
const navigation = [
  { label: 'Overview', link: '/' },
  { label: 'Getting started', expanded: true, items: [
    { label: 'Overview', link: '/getting-started/' },
    { label: 'Using the API', items: [
      { label: 'Overview', link: '/getting-started/using-the-api/' },
      { label: 'Auth & API Keys', link: '/getting-started/using-the-api/api-keys/' },
      { label: 'Permissions', link: '/getting-started/using-the-api/permissions/' },
      { label: 'Rate limits', link: '/getting-started/using-the-api/rate-limits/' },
    ] },
    { label: 'URL to Image', link: '/getting-started/url-to-image/' },
    { label: 'Setting height and width', link: '/getting-started/setting-height-and-width/' },
    { label: 'Open Graph Images', items: [
      { label: 'Overview', link: '/getting-started/og-images/' },
      { label: 'Supported parameters', link: '/getting-started/og-images/supported-parameters/' },
    ] },
    { label: 'Image templates', link: '/getting-started/templates/' },
    { label: 'Signed image URLs', link: '/getting-started/create-and-render/' },
  ] },
  { label: 'Management API', items: [
    { label: 'Overview', link: '/management-api/' },
    { label: 'API key management', link: '/management-api/api-keys/' },
    { label: 'Usage and limits', link: '/management-api/usage/' },
    { label: 'Proxies API', link: '/management-api/proxies/' },
    { label: 'Storage destinations API', link: '/management-api/storage-destinations/' },
    { label: 'OG configurations API', link: '/management-api/og-configs/' },
    { label: 'Infrastructure as code', items: [
      { label: 'Overview', link: '/management-api/iac/' },
      { label: 'Terraform', link: '/management-api/terraform/' },
      { label: 'Pulumi', link: '/management-api/pulumi/' },
    ] },
  ] },
  { label: 'Parameters', items: [
    { label: 'Overview', link: '/parameters/' },
    { label: 'color_scheme', link: '/parameters/color_scheme/' },
    { label: 'dedupe_duration_s', link: '/parameters/dedupe_duration_s/' },
    { label: 'device_scale', link: '/parameters/device_scale/' },
    { label: 'format', link: '/parameters/format/' },
    { label: 'full_screen', link: '/parameters/full_screen/' },
    { label: 'google_fonts', link: '/parameters/google_fonts/' },
    { label: 'headers', link: '/parameters/headers/' },
    { label: 'identify_as_hcti', link: '/parameters/identify_as_hcti/' },
    { label: 'max_wait_ms', link: '/parameters/max_wait_ms/' },
    { label: 'media_type', link: '/parameters/media_type/' },
    { label: 'ms_delay', link: '/parameters/ms_delay/' },
    { label: 'pdf_options', link: '/parameters/pdf_options/' },
    { label: 'proxy_id', link: '/parameters/proxy_id/' },
    { label: 'render_when_ready', link: '/parameters/render_when_ready/' },
    { label: 'selector', link: '/parameters/selector/' },
    { label: 'storage_destination_id', link: '/parameters/storage_destination_id/' },
    { label: 'timezone', link: '/parameters/timezone/' },
    { label: 'transparent_background', link: '/parameters/transparent_background/' },
    { label: 'Jumbo Images', link: '/guides/advanced/jumbo-images/' },
    { label: 'Viewport', link: '/parameters/viewport/' },
    { label: 'dl', link: '/parameters/dl/' },
  ] },
  { label: 'Template Editor', items: [
    { label: 'Overview', link: '/template-editor/' },
    { label: 'Quick start', link: '/template-editor/quick-start/' },
    { label: 'Canvas', link: '/template-editor/canvas/' },
    { label: 'Variables', link: '/template-editor/variables/' },
    { label: 'Blocks', items: [
      { label: 'Overview', link: '/template-editor/blocks/' },
      { label: 'Rich Text', link: '/template-editor/blocks/rich-text/' },
      { label: 'Simple Text', link: '/template-editor/blocks/simple-text/' },
      { label: 'Image', link: '/template-editor/blocks/image/' },
      { label: 'Shape', link: '/template-editor/blocks/shape/' },
      { label: 'HTML', link: '/template-editor/blocks/html/' },
      { label: 'Free Panel', link: '/template-editor/blocks/free-panel/' },
      { label: 'Flex Panel', link: '/template-editor/blocks/flex-panel/' },
      { label: 'Grid Panel', link: '/template-editor/blocks/grid-panel/' },
      { label: 'Table Panel', link: '/template-editor/blocks/table-panel/' },
    ] },
    { label: 'Advanced', items: [
      { label: 'Overview', link: '/template-editor/advanced/' },
      { label: 'Sizing and positioning', link: '/template-editor/advanced/sizing-positioning/' },
      { label: 'Panels', link: '/template-editor/advanced/panels/' },
      { label: 'Extra CSS', link: '/template-editor/advanced/extra-css/' },
    ] },
  ] },
  { label: 'Example code', items: [
    { label: 'Overview', link: '/example-code/' },
    { label: 'cURL', link: '/example-code/curl/' },
    { label: 'JavaScript', link: '/example-code/javascript/' },
    { label: 'TypeScript', link: '/example-code/typescript/' },
    { label: 'Python', link: '/example-code/python/' },
    { label: 'PHP', link: '/example-code/php/' },
    { label: 'Ruby', link: '/example-code/ruby/' },
    { label: 'Go', link: '/example-code/go/' },
    { label: 'C# / .NET', link: '/example-code/c/' },
    { label: 'VB.NET', link: '/example-code/vb.net/' },
    { label: 'Java', link: '/example-code/java/' },
    { label: 'Kotlin', link: '/example-code/kotlin/' },
    { label: 'Rust', link: '/example-code/rust/' },
    { label: 'Elixir', link: '/example-code/elixir/' },
    { label: 'Google Apps Script', link: '/example-code/google-apps-script/' },
  ] },
  { label: 'Use cases', items: [
    { label: 'Overview', link: '/use-cases/' },
    { label: 'Social cards', link: '/use-cases/social-cards/' },
    { label: 'Screenshots', link: '/use-cases/screenshots/' },
    { label: 'Dynamic images', link: '/use-cases/dynamic-images/' },
  ] },
  { label: 'Integrations', items: [
    { label: 'Overview', link: '/integrations/' },
    { label: 'n8n', link: '/integrations/n8n/' },
    { label: 'Zapier', link: '/integrations/zapier/' },
    { label: 'Make', link: '/integrations/make/' },
    { label: 'MCP server', items: [
      { label: 'Overview', link: '/integrations/mcp/' },
      { label: 'Tools reference', link: '/integrations/mcp/tools/' },
      { label: 'Permissions', link: '/integrations/mcp/permissions/' },
      { label: 'ChatGPT & Codex', link: '/integrations/mcp/chatgpt-codex/' },
      { label: 'Claude & Claude Code', link: '/integrations/mcp/claude/' },
      { label: 'Cline', link: '/integrations/mcp/cline/' },
      { label: 'Cursor', link: '/integrations/mcp/cursor/' },
      { label: 'Gemini CLI', link: '/integrations/mcp/gemini/' },
      { label: 'GitHub Copilot', link: '/integrations/mcp/github-copilot/' },
      { label: 'Grok', link: '/integrations/mcp/grok/' },
      { label: 'JetBrains IDEs', link: '/integrations/mcp/jetbrains/' },
      { label: 'OpenCode', link: '/integrations/mcp/opencode/' },
      { label: 'VS Code', link: '/integrations/mcp/vscode/' },
      { label: 'Windsurf', link: '/integrations/mcp/windsurf/' },
      { label: 'Zed', link: '/integrations/mcp/zed/' },
    ] },
  ] },
  { label: 'Guides', items: [
    { label: 'Overview', link: '/guides/' },
    { label: 'OG Images', items: [
      { label: 'Overview', link: '/guides/og-images/' },
      { label: 'Shopify', link: '/guides/og-images/shopify/' },
      { label: 'Squarespace', link: '/guides/og-images/squarespace/' },
      { label: 'Webflow', link: '/guides/og-images/webflow/' },
      { label: 'Wix', link: '/guides/og-images/wix/' },
      { label: 'WordPress', link: '/guides/og-images/wordpress/' },
      { label: 'Jekyll', link: '/guides/og-images/jekyll/' },
      { label: 'Astro', link: '/guides/og-images/astro/' },
      { label: 'Sitepress', link: '/guides/og-images/sitepress/' },
    ] },
    { label: 'Debugging', items: [
      { label: 'Overview', link: '/guides/debugging/' },
      { label: 'Blurry images', link: '/guides/debugging/blurry-images/' },
      { label: 'Cropping issues', link: '/guides/debugging/cropping-issues/' },
      { label: 'White images', link: '/guides/debugging/white-images/' },
      { label: 'Emoji', link: '/guides/debugging/emoji/' },
      { label: 'Cloudflare challenges', link: '/guides/debugging/cloudflare-challenges/' },
      { label: 'OG Image caching', link: '/guides/debugging/og-image-caching/' },
    ] },
    { label: 'Styling', items: [
      { label: 'Overview', link: '/guides/styling/' },
      { label: 'External CSS and fonts', link: '/guides/styling/external-css-fonts/' },
      { label: 'File formats', link: '/guides/styling/file-formats/' },
      { label: 'Transparent backgrounds', link: '/guides/styling/transparent-background/' },
    ] },
    { label: 'Social media', items: [
      { label: 'Overview', link: '/guides/social-media/' },
      { label: 'Twitter / X', link: '/guides/social-media/twitter/' },
      { label: 'Facebook', link: '/guides/social-media/facebook/' },
      { label: 'Instagram', link: '/guides/social-media/instagram/' },
      { label: 'LinkedIn', link: '/guides/social-media/linkedin/' },
    ] },
    { label: 'Workflows', items: [
      { label: 'Overview', link: '/guides/workflows/' },
      { label: 'Email to images', link: '/guides/workflows/email-to-images/' },
      { label: 'Email to Slack', link: '/guides/workflows/email-to-slack/' },
      { label: 'Highcharts', link: '/guides/workflows/highcharts/' },
      { label: 'Insomnia', link: '/guides/workflows/insomnia/' },
      { label: 'Postman', link: '/guides/workflows/postman/' },
    ] },
    { label: 'Advanced', items: [
      { label: 'Overview', link: '/guides/advanced/' },
      { label: 'Base64 images', link: '/guides/advanced/base64/' },
      { label: 'Cookie banners', link: '/guides/advanced/blocking-cookie-banners/' },
      { label: 'Duplicate detection', link: '/guides/advanced/duplicate-detection/' },
      { label: 'Jumbo Images', link: '/guides/advanced/jumbo-images/' },
      { label: 'Proxies', link: '/guides/advanced/proxies/' },
      { label: 'Storage destinations', items: [
        { label: 'Overview', link: '/guides/advanced/storage-destinations/' },
        { label: 'Amazon S3', link: '/guides/advanced/storage-destinations/s3/' },
        { label: 'Cloudflare R2', link: '/guides/advanced/storage-destinations/r2/' },
        { label: 'Backblaze B2', link: '/guides/advanced/storage-destinations/backblaze-b2/' },
        { label: 'DigitalOcean Spaces', link: '/guides/advanced/storage-destinations/digitalocean-spaces/' },
        { label: 'Google Cloud Storage', link: '/guides/advanced/storage-destinations/google-cloud-storage/' },
        { label: 'Wasabi', link: '/guides/advanced/storage-destinations/wasabi/' },
        { label: 'S3-compatible storage', link: '/guides/advanced/storage-destinations/s3-compatible/' },
      ] },
    ] },
    { label: 'Account', items: [
      { label: 'Overview', link: '/guides/account/' },
      { label: 'Account settings', link: '/guides/account/account-settings/' },
      { label: 'Organization settings', link: '/guides/account/organization-settings/' },
    ] },
  ] },
  { label: 'FAQ', link: '/faq/' },
  { label: 'Changelog', link: '/changelog/' },
];

// Author groups with expanded: true only when they should open by default.
// Starlight still opens the ancestors of the currently selected page.
function starlightItems(items) {
  return items.map(({ expanded = false, items: children, ...item }) =>
    children
      ? { ...item, collapsed: !expanded, items: starlightItems(children) }
      : item
  );
}

export default starlightItems(navigation);
